pipeline:
  depend:
    image: debian:stretch
    commands:
    	- apt update; apt install gcc git make libglib2.0-bin libgtk-3-dev libxml2-utils -y
      
  build:
    image: debian:stretch
    commands:
    	- make
        
  checksum:
    image: debian:stretch
    commands:
    	- sha512sum -c sha512.sum

