version: 1
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install packages
          command: apt update; apt install gcc git make libglib2.0-bin libgtk-3-dev libxml2-utils
      - run:
          name: Build binary
          command: make
