version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install packages
          command: apt update; apt install gcc git make libglib2.0-bin libgtk-3-dev libxml2-utils -y
      - run:
          name: Build binary
          command: make
      - run:
          name: Checksum
          command: sha512sum -c sha512.sum
      - store_artifacts:
          path: rdg
          prefix: rdg-binary
      - store_artifacts:
          path: sha512.sum
          prefix: rdg-checksum
