version: 2
jobs:
  build:
    docker:
      - image: ubuntu:xenial
    steps:
      - checkout
      - run:
          name: Install packages
          command: apt-get install gcc git make libglib2.0-bin libgtk-3-dev libxml2-utils
      - run:
          name: Build binary
          command: make
